### ISSUE TITLE
SignIns Unknown Requirement Provider

### ISSUE THREAD

**Issue by L4r1k** [microsoftgraph/msgraph-beta-sdk-go#391]
Hi,

Similar to the issue [here](https://github.com/microsoftgraph/msgraph-sdk-go/issues/617) I'm suddenly getting the following error when retrieving sign in logs: 

```
Unknown RequirementProvider value: authenticationStrengths
```

I think this may be another metadata issue where the SDK is not recognizing the `authenticationRequirementPolicies` block when it contains a `requirementProvider` of `authenticationStrengths`:

```json
...,
"authenticationRequirementPolicies": [
    {
        "requirementProvider": "multiConditionalAccess",
        "detail": "Conditional Access"
    },
    {
        "requirementProvider": "authenticationStrengths",
        "detail": "Authentication Strength(s)"
    }
],
...
```

**Comment by baywet** [comment]
Hi @L4r1k 
Thanks for reporting this one as well.
Can you provide the API path and operation you're calling please so we can identify the target service and let them know?

**Comment by L4r1k** [comment]
[This](https://learn.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&tabs=http) is the endpoint (List SignIns)

**Comment by baywet** [comment]
Thank you for the details, just created the following ICM (you won't be able to access this link) so the service team corrects the metadata https://portal.microsofticm.com/imp/v3/incidents/incident/477405317/summary

**Comment by L4r1k** [comment]
Hi @baywet, any updates on the ICM?

**Comment by baywet** [comment]
it's still hasn't been acknowledged by the service team, I reached out directly to the on call engineer to understand what's going on.

**Comment by baywet** [comment]
Update: the incident was originally routed to the wrong team. Now it's been picked up by the right one and they started deploying a fix.
Hopefully this fix is deployed by next week, and our weekly generation process picks it up by the next one

**Comment by L4r1k** [comment]
@baywet I'm still seeing the same error after updating to the latest version of the beta SDK

**Comment by baywet** [comment]
After circling back with the service team we established it was deployed a little AFTER our SDKs generation started this week.
It should be part of next week's release. Thank you for your patience and for confirming.

**Comment by L4r1k** [comment]
@baywet I updated to build `0.101.0` released a few hours ago and am still experiencing this issue

**Comment by baywet** [comment]
Thanks for the nudge!

@marabooy We might have an issue with the weekly metadata sync process here.

The enum member authenticationStrengths for enum requirementProvider is present in the [beta public metadata](https://graph.microsoft.com/beta/$metadata) but absent from [the weekly sync file](https://github.com/microsoftgraph/msgraph-metadata/blob/master/schemas/annotated-beta-Prod.csdl) would you mind looking into it please?

**Comment by baywet** [comment]
@L4r1k after investigation from the deployment team, it seems that the exports of the metadata were missing some kinds of deployments.
This had been addressed and the enum member is now present in the metadata!!!
https://github.com/microsoftgraph/msgraph-metadata/pull/615/files#diff-1b090701470d83823abd17127d457a60b22ec2dab8a8e3d74ff808273a0a5938R7537

Next week should be the right one! Thank you again for the reminders and the extended patience!

**Comment by L4r1k** [comment]
This one appears to be resolved in v`0.102.0` @baywet , thanks for you help again!

**Comment by baywet** [comment]
Thanks for confirming! closing
